// src/app/about/contacts/page.tsx
import Image from 'next/image';
import Link from 'next/link';

import SubTitle from '@/components/common/sub-title';
import icons from '@/components/icons';

export default function Home() {
  const size = 'h-16 w-16 min-w-16 min-h-16';
  return (
    <div className="border-b border-bgSt py-4">
      <SubTitle text="Contacts" />
      <div className="my-4 flex w-3/4 justify-around">
        <Link href={`/validator/1`} className={size}>
          <Image src={icons.CW3Icon} alt="control" className={size} />
        </Link>
        <Link href="https://github.com/citizenweb3" className={size} target="_blank">
          <Image src={icons.GithubIcon} alt="Citizen Web 3 github" className={size} />
        </Link>
        <Link href="https://x.com/citizen_web3" className={size} target="_blank">
          <Image src={icons.XIcon} alt="Citizen Web 3 X" className={size} />
        </Link>
      </div>
      <div className="mt-8 flex flex-row items-center">
        <Image src="/img/icons/email.svg" alt="email" width={16} height={16} className="mr-1 h-4 w-4" />
        <Link href="mailto:ping@validatorinfo.com" className="text-base">
          ping@validatorinfo.com
        </Link>
      </div>
    </div>
  );
}

// src/modules/aboutUs/components/Contacts.vue
<template>
  <div class="titleWrapper"><p class="title px-4">Contacts</p></div>
  <div class="contentWrapper mt-9 pb-3">
    <div class="flex ml-10">
      <a href="https://www.citizenweb3.com/" class="mr-8"
        ><icon-base icon-name="citizen" width="40" height="40"><icon-citizen /></icon-base
      ></a>
      <a href="https://github.com/citizenweb3" class="mr-8">
        <icon-base icon-name="github" width="40" height="40"><icon-github /></icon-base
      ></a>
      <a href="https://twitter.com/citizen_web3" class="mr-8"
        ><icon-base icon-name="x" width="40" height="40"><icon-x /></icon-base
      ></a>
    </div>
    <div class="flex align-bottom items-center mt-5">
      <icon-base icon-name="email" class="mr-1"><icon-email /></icon-base>
      <p class="text-white"><a href="ping@validatorinfo.com">ping@validatorinfo.com</a></p>
    </div>
  </div>
</template>

<script lang="ts" setup>
import IconBase from 'components/Icons/IconBase.vue'
</script>

<style scoped lang="scss">
.contentWrapper {
  border-bottom: 1px solid theme('colors.blackOlive');
}
</style>
