// src/app/about/staking/page.tsx
import Link from 'next/link';

import Button from '@/components/common/button';
import SubTitle from '@/components/common/sub-title';

export default function Home() {
  return (
    <div>
      <SubTitle text="Staking" />
      <div className="flex flex-row items-center border-b border-bgSt py-4">
        <div className="text-[4rem] text-[#F20000]">?</div>
        <div className="ml-12 mt-4 text-base">
          Validator info is fully sponsored by the Citizen Web3 validator. Citizen Web3 monetizes itself via staking.
          <br />
          <br />
          Citizen Web3 helps to secure blockchain networks by providing infrastructure. This includes validator,
          testnet, and various public access nodes.
          <br />
          <br />
          We use Multi-party computation software (Horcrux) on all our nodes, to further secure funds, and protect
          stakers from double signing. We use Re-Stake on all of our mainnet nodes, set to restake twice per day, so
          users can compound their staking rewards more efficiently. Our current target is moving 95% of our
          infrastructure to (own) baremetal by spring 2024. We strongly believe in decentralized infrastructure,
          independent of the grid, and thats our end goal.
          <br />
          <br />
          Token holders of networks we validate, can stake with us to help secure these networks and to support our
          activities. Their incentive for doing so, is earning staking rewards, and other, planned, incentives in the
          future. We are devoted to our mission, we think out of the box, and are proud to be a little crazy. We value
          security, decentralization, privacy and lack of enforcement.
        </div>
      </div>
      <SubTitle text="Network" size="h3" />
      <div className="border-b border-bgSt py-4">
        {Object.keys(data).map((title) => (
          <div key={title} className="mx-6 text-base">
            <SubTitle text={title} size="h4" />
            <ul className="ml-4 mt-6 list-disc">
              {data[title].map(({ name, link, stake, info, rpc, additional }) => (
                <li key={name}>
                  {link ? (
                    <Link href={link} target="_blank" className="border-b border-bgSt hover:border-white">
                      {name}
                    </Link>
                  ) : (
                    name
                  )}
                  {stake && (
                    <>
                      <span className="px-2">|</span>
                      <Link href={stake} target="_blank" className="border-b border-bgSt hover:border-white">
                        Stake
                      </Link>
                    </>
                  )}
                  {info && (
                    <>
                      <span className="px-2">|</span>
                      <Link href={info} target="_blank" className="border-b border-bgSt hover:border-white">
                        Info
                      </Link>
                    </>
                  )}

                  {rpc && (
                    <>
                      <span className="px-2">|</span>
                      <Link href={rpc} target="_blank" className="border-b border-bgSt hover:border-white">
                        RPC
                      </Link>
                    </>
                  )}
                  {additional && (
                    <>
                      <span className="px-2">|</span>
                      {additional}
                    </>
                  )}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
      <SubTitle text="Dao Stakes" size="h3" />
      <Button className="ml-12 mt-4 text-lg">Learn more</Button>
    </div>
  );
}

const data: Record<
  string,
  { name: string; link?: string; stake?: string; info?: string; additional?: string; rpc?: string }[]
> = {
  Mainnet: [
    {
      name: 'Cosmos hub',
      stake:
        'https://wallet.keplr.app/chains/cosmos-hub?modal=staking&chain=cosmoshub-4&validator_address=cosmosvaloper1e859xaue4k2jzqw20cv6l7p3tmc378pc3k8g2u&step_id=3&action_id=stake',
      info: '/',
    },
    { name: 'Celestia', stake: '/', info: '/' },
    {
      name: 'Evmos',
      stake:
        'https://wallet.keplr.app/chains/evmos?modal=staking&chain=evmos_9001-2&validator_address=evmosvaloper1mtwvpdd57gpkyejd566s24afr9zm5ryq8gwpvj&step_id=3&action_id=stake',
      info: '/',
      additional: 'Genesis Validator',
    },
    {
      name: 'LikeCoin',
      stake:
        'https://wallet.keplr.app/chains/likecoin?modal=staking&chain=likecoin-mainnet-2&validator_address=likevaloper136r5phdpc02gmtmyampl9qkv0mdq385xxsaadu&step_id=3&action_id=stake',
      info: '/',
    },
    { name: 'BitCanna', stake: '/', info: '/' },
    {
      name: 'Cyber/Bostrom',
      stake:
        'https://wallet.keplr.app/chains/bostrom?modal=staking&chain=bostrom&validator_address=bostromvaloper1f7nx65pmayfenpfwzwaamwas4ygmvalqj6dz5r&step_id=3&action_id=stake',
      info: '/',
      additional: 'Pre-Genesis & Genesis Validator',
    },
    {
      name: 'Gravity Bridge',
      stake:
        'https://wallet.keplr.app/chains/gravity-bridge?modal=staking&chain=gravity-bridge-3&validator_address=gravityvaloper1a00v3m5sthed82267gvdp2qt9czhjngg2djy8m&step_id=3&action_id=stake',
      info: '/',
    },
    { name: 'Composable', stake: '/', info: '/' },
    { name: 'Dymension', stake: '/', info: '/', additional: 'Pre-Genesis & Genesis Validator' },
  ],
  ICS: [
    { name: 'Neutron', info: '/' },
    { name: 'Stride', info: '/' },
  ],
  'Incitivezed Testnet / Stakenet': [
    { name: 'Namada', info: '/', additional: 'Pre-Genesis validator (Shielded Expedition)' },
    { name: 'Nomic', stake: '/', info: '/', additional: 'Stakenet' },
    { name: 'Soarchain', info: '/', additional: 'Pre-Genesis validator' },
  ],
  Testnet: [{ name: 'Althea', info: '/', additional: 'Pre-Genesis validator' }],
  'Public endpoints': [
    { name: 'BitCanna', rpc: '/' },
    { name: 'LikeCoin', rpc: '/' },
  ],
  Relayer: [{ name: 'Bostrom - Osmosis', link: '/', additional: 'Stopped for now' }],
  Researching: [{ name: 'List', link: '/', additional: 'Long term research' }],
};

// src/modules/aboutUs/components/Staking.vue
<template>
  <div>
    <p class="title">{{ data.title }}</p>
  </div>
  <div class="contentWrapper mt-4">
    <div class="description pb-5">
      <div class="ml-10">
        <p class="text-white mt-3 leading-6">
          Validator info is fully sponsored by the Citizen Web3 validator. Citizen Web3 monetizes
          itself via staking.
        </p>

        <p class="text-white mt-3 leading-6">
          Citizen Web3 helps to secure blockchain networks by providing infrastructure. This
          includes validator, testnet, and various public access nodes.
        </p>

        <p class="text-white mt-3 leading-6">
          We use Multi-party computation software
          <a href="https://github.com/strangelove-ventures/horcrux">(Horcrux)</a> on all our nodes,
          to further secure funds, and protect stakers from double signing.
        </p>

        <p class="text-white mt-3 leading-6">
          We use <a href="https://restake.app/">Re-Stakeon</a> all of our mainnet nodes, set to
          restake twice per day, so users can compound their staking rewards more efficiently. Our
          current target is moving 95% of our infrastructure to (own) baremetal by spring 2024. We
          strongly believe in decentralized infrastructure, independent of the grid, and thats our
          end goal.
        </p>

        <p class="text-white mt-3 leading-6">
          Token holders of networks we validate, can stake with us to help secure these networks and
          to support our activities. Their incentive for doing so, is earning staking rewards, and
          other, <a href="https://github.com/citizenweb3/super-pancake/issues">planned</a>,
          incentives in the future. We are devoted to our
          <a href="https://github.com/citizenweb3#tldr">mission</a>, we think out of the box, and
          are proud to be a little crazy. We value security, decentralization, privacy and lack of
          enforcement.
        </p>
      </div>
    </div>
    <div class="description pb-5">
      <div>
        <p class="title text-h3">Network</p>
      </div>
      <div class="listGroup">
        <p class="titleGroup">Mainet:</p>
        <ul>
          <li>
            Cosmos hub:
            <a
              href="https://wallet.keplr.app/chains/cosmos-hub?modal=validator&amp;chain=cosmoshub-4&amp;validator_address=cosmosvaloper1e859xaue4k2jzqw20cv6l7p3tmc378pc3k8g2u&amp;referral=true"
              rel="nofollow"
              >Stake</a
            >
            |
            <a
              href="https://www.mintscan.io/cosmos/validators/cosmosvaloper1e859xaue4k2jzqw20cv6l7p3tmc378pc3k8g2u"
              rel="nofollow"
              >Info</a
            >
          </li>
          <li>
            Celestia:
            <a
              href="https://wallet.keplr.app/chains/celestia?modal=validator&amp;chain=celestia&amp;validator_address=celestiavaloper1m77eksxfz9q50qejnqf720sns7q0xtx8uzxnhs"
              rel="nofollow"
              >Stake</a
            >
            |
            <a
              href="https://www.mintscan.io/cosmos/validators/cosmosvaloper1e859xaue4k2jzqw20cv6l7p3tmc378pc3k8g2u"
              rel="nofollow"
              >Info</a
            >
          </li>
          <li>
            Evmos:
            <a
              href="https://wallet.keplr.app/chains/evmos?modal=validator&amp;chain=evmos_9001-2&amp;validator_address=evmosvaloper1mtwvpdd57gpkyejd566s24afr9zm5ryq8gwpvj&amp;referral=true"
              rel="nofollow"
              >Stake</a
            >
            |
            <a
              href="https://www.mintscan.io/evmos/validators/evmosvaloper1mtwvpdd57gpkyejd566s24afr9zm5ryq8gwpvj"
              rel="nofollow"
              >Info</a
            >
            | Genesis Validator
          </li>
          <li>
            LikeCoin:
            <a
              href="https://wallet.keplr.app/chains/likecoin?modal=validator&amp;chain=likecoin-mainnet-2&amp;validator_address=likevaloper136r5phdpc02gmtmyampl9qkv0mdq385xxsaadu"
              rel="nofollow"
              >Stake</a
            >
            |
            <a
              href="https://www.mintscan.io/likecoin/validators/likevaloper136r5phdpc02gmtmyampl9qkv0mdq385xxsaadu"
              rel="nofollow"
              >Info</a
            >
          </li>
          <li>
            BitCanna:
            <a
              href="https://wallet.bitcanna.io/validators/bcnavaloper1ngt4atd3qlgcwfv7fkjdjxhz7k0vl2rejrvzye"
              rel="nofollow"
              >Stake</a
            >
            |
            <a
              href="https://www.mintscan.io/bitcanna/validators/bcnavaloper1ngt4atd3qlgcwfv7fkjdjxhz7k0vl2rejrvzye"
              rel="nofollow"
              >Info</a
            >
          </li>
          <li>
            Cyber/Bostrom:
            <a
              href="https://wallet.keplr.app/chains/bostrom?modal=validator&amp;chain=bostrom&amp;validator_address=bostromvaloper1f7nx65pmayfenpfwzwaamwas4ygmvalqj6dz5r&amp;referral=true"
              rel="nofollow"
              >Stake</a
            >
            |
            <a
              href="https://cyb.ai/network/bostrom/hero/bostromvaloper1f7nx65pmayfenpfwzwaamwas4ygmvalqj6dz5r"
              rel="nofollow"
              >Info</a
            >
            | Pre-Genesis &amp; Genesis Validator
          </li>
          <li>
            Gravity Bridge:
            <a
              href="https://wallet.keplr.app/chains/gravity-bridge?modal=validator&amp;chain=gravity-bridge-3&amp;validator_address=gravityvaloper1a00v3m5sthed82267gvdp2qt9czhjngg2djy8m"
              rel="nofollow"
              >Stake</a
            >
            |
            <a
              href="https://www.mintscan.io/gravity-bridge/validators/gravityvaloper1a00v3m5sthed82267gvdp2qt9czhjngg2djy8m"
              rel="nofollow"
              >Info</a
            >
          </li>
          <li>
            Composable:
            <a
              href="https://explorer.nodestake.org/composable/staking/centaurivaloper1u96ny0k6c9lnsr66q2hleyu58nhvuurk9rx0dk"
              rel="nofollow"
              >Stake</a
            >
            |
            <a
              href="https://explorer.nodestake.org/composable/staking/centaurivaloper1u96ny0k6c9lnsr66q2hleyu58nhvuurk9rx0dk"
              rel="nofollow"
              >Info</a
            >
          </li>
          <li>
            Dymension:
            <a href="https://portal.dymension.xyz/dymension/staking" rel="nofollow">Stake</a>
            |
            <a
              href="https://dymension.explorers.guru/validator/dymvaloper1z3et7f750ym0cnvxcp7f8lsyynnmk82ts8ljzg"
              rel="nofollow"
              >Info</a
            >
            | Pre-Genesis &amp; Genesis Validator
          </li>
        </ul>
      </div>
      <div class="listGroup">
        <p class="titleGroup">ICS:</p>
        <ul>
          <li>
            Neutron:
            <a
              href="https://www.mintscan.io/neutron/ics-validators/cosmosvaloper1e859xaue4k2jzqw20cv6l7p3tmc378pc3k8g2u"
              rel="nofollow"
              >Info</a
            >
          </li>
          <li>
            Stride:
            <a
              href="https://www.mintscan.io/stride/ics-validators/cosmosvaloper1e859xaue4k2jzqw20cv6l7p3tmc378pc3k8g2u"
              rel="nofollow"
              >Info</a
            >
          </li>
        </ul>
      </div>
      <div class="listGroup">
        <p class="titleGroup">Incitivezed Testnet / Stakenet:</p>
        <ul>
          <li>
            Namada:
            <a
              href="https://namada.info/validator/BAF27407725385D4930D53A95036FE1C284A2AC5"
              rel="nofollow"
              >Info</a
            >
            | Pre-Genesis validator (Shielded Expedition)
          </li>
          <li>
            Nomic:
            <a
              href="https://app.nomic.io/staking?validator=nomic1mk05ju8jq0mxzx3kfr0wcct8an2htjh53m4yk5&amp;modal=info"
              rel="nofollow"
              >Stake</a
            >
            |
            <a
              href="https://nomic-explorer.quokkastake.io/nomic/staking/nomic1mk05ju8jq0mxzx3kfr0wcct8an2htjh53m4yk5"
              rel="nofollow"
              >Info</a
            >
            | Stakenet
          </li>
          <li>
            Soarchain:
            <a
              href="https://explorer.soarchain.com/soar/staking/soarvaloper1z66ujcpjxppue2u4pflwhakh0he4qup63586cx"
              rel="nofollow"
              >Info</a
            >
            | Pre-Genesis validator
          </li>
          <li>
            GoVGen:
            <a
              href="https://explorer.govgen.io/govgen/staking/govgenvaloper1m77eksxfz9q50qejnqf720sns7q0xtx8pv6wce"
              rel="nofollow"
              >Stake</a
            >
            |
            <a
              href="https://explorer.govgen.io/govgen/staking/govgenvaloper1m77eksxfz9q50qejnqf720sns7q0xtx8pv6wce"
              rel="nofollow"
              >Info</a
            >
            | Pre-Genesis validator. Pre launch chain
          </li>
        </ul>
      </div>
      <div class="listGroup">
        <p class="titleGroup">Testnet:</p>
        <ul>
          <li>
            Althea:
            <a
              href="https://exp.nodeist.net/Althea/staking/altheavaloper15v29dfawte5hzv9xr72tfcxwp679u7agvhhmkn"
              rel="nofollow"
              >Stake</a
            >
            |
            <a
              href="https://exp.nodeist.net/Althea/staking/altheavaloper15v29dfawte5hzv9xr72tfcxwp679u7agvhhmkn"
              rel="nofollow"
              >Info</a
            >
            | Pre-Genesis validator
          </li>
        </ul>
      </div>
      <div class="listGroup">
        <p class="titleGroup">Public endpoints:</p>
        <ul>
          <li>
            BitCanna:
            <a href="http://rpc.bitcanna.citizencosmos.space/" rel="nofollow">RPC</a>
          </li>
          <li>Likecoin: <a href="http://51.159.223.25:28657" rel="nofollow">RPC</a></li>
        </ul>
      </div>
      <div class="listGroup">
        <p class="titleGroup">Relayer:</p>
        <ul>
          <li>
            <a
              href="https://wallet.keplr.app/chains/cosmos-hub?modal=validator&chain=cosmoshub-4&validator_address=cosmosvaloper1e859xaue4k2jzqw20cv6l7p3tmc378pc3k8g2u&referral=true"
              >Bostrom - Osmosis</a
            >: Stopped for now
          </li>
        </ul>
      </div>
      <div class="listGroup">
        <p class="titleGroup">Researching:</p>
        <ul>
          <li>
            <a href="https://github.com/citizenweb3/staking/issues/44" rel="nofollow">List</a>: Long
            term research
          </li>
        </ul>
      </div>
    </div>
    <div class="description pb-5 mb-5">
      <div
        v-for="(value, index) in data.data.section"
        :key="index"
        class="relative hover:z-10"
        :class="'z-' + index"
      >
        <p class="title">{{ value.title }}</p>
        <div class="mt-4 ml-6"><Button :text="value.textButton" :round="true" /></div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import useStore from 'store'
import { StakingInfo } from 'modules/aboutUs/store/types'
import ContentItem from 'modules/aboutUs/components/ContentItem.vue'
import Button from 'components/Button/index.vue'
const store = useStore()

export default defineComponent({
  name: 'AboutUsStaking',
  components: {
    Button,
    ContentItem,
  },
  props: {
    title: {
      type: String,
      default: 'Staking tabs',
    },
  },
  setup() {
    const data: StakingInfo = store.aboutUs.staking

    return {
      data,
    }
  },
})
</script>

<style scoped lang="scss">
.title {
  color: theme('colors.americanYellow');
  font-size: 24px;
  border-bottom: 1px solid theme('colors.blackOlive');
  width: fit-content;
  padding: 0 1rem;
}
.description {
  color: white !important;
  border-bottom: 1px solid theme('colors.blackOlive');
}

.listGroup {
  @apply ml-6 #{!important};
  .titleGroup {
    @apply my-4 text-orange #{!important};
  }
}
a {
  text-decoration: underline;
}
</style>
