// src/app/components/footer.tsx
import Image from 'next/image';
import Link from 'next/link';
import { FC } from 'react';

import icons from '@/components/icons';

interface OwnProps {}

const Header: FC<OwnProps> = ({}) => {
  const size = 'h-9 w-9 min-w-9 min-h-9';
  return (
    <div className="my-4 flex justify-end space-x-1">
      <Link href="https://www.citizenweb3.com/about" className={size} target="_blank">
        <Image src={icons.CW3Icon} alt="control" className={size} />
      </Link>
      <Link href="https://github.com/citizenweb3/validatorinfo" className={size} target="_blank">
        <Image src={icons.GithubIcon} alt="Citizen Web 3 github" className={size} />
      </Link>
      <Link href="https://twitter.com/therealvalidatorinfo" className={size} target="_blank">
        <Image src={icons.XIcon} alt="Citizen Web 3 X" className={size} />
      </Link>
    </div>
  );
};

export default Header;

// src/components/Footer/index.vue
<template>
  <div class="wrapper">
    <div class="links">
      <a href="https://www.citizenweb3.com/"><CitizenIcon /></a>
      <a href="https://github.com/citizenweb3" class="mx-2"><GithubIcon /></a>
      <a href="https://twitter.com/citizen_web3"><XIcon /></a>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

import XIcon from '@/components/Icons/x.vue'
import GithubIcon from '@/components/Icons/github.vue'
import CitizenIcon from '@/components/Icons/citizen.vue'

export default defineComponent({
  name: 'Footer',
  components: {
    XIcon,
    GithubIcon,
    CitizenIcon,
  },
  setup() {
    return {}
  },
})
</script>

<style scoped lang="scss">
.wrapper {
  width: 100%;
  height: 100px;

  display: flex;
  justify-content: flex-end;
}
.links {
  display: flex;
  flex-direction: row;
}
</style>
